kernel: process: remove unused function after c702f943914d1bdcfa1b78acb15fd2ba6a5f1cb8
error: unused function '__cpu_do_idle_irqprio' [-Werror,-Wunused-function]
   89 | static void __cpu_do_idle_irqprio(void)
      |             ^~~~~~~~~~~~~~~~~~~~~
1 error generated.

Signed-off-by: onettboots <blackcocopet@gmail.com>