sched: Makefile: disable cast to smaller integer type error
Unsure if my previous "fix" of using uintptr resolves it or causes problems

../kernel/sched/walt.c:3177:30: error: cast to smaller integer type 'unsigned int' from 'void *' [-Werror,-Wvoid-pointer-to-int-cast]
        unsigned int profile_mode = (unsigned int)data;
                                    ^~~~~~~~~~~~~~~~~~
1 error generated.