char: random: fix unused function error
../drivers/char/random.c:1036:16: error: unused function 'extract_crng_user' [-Werror,-Wunused-function]
static ssize_t extract_crng_user(void __user *buf, size_t nbytes)
               ^
1 error generated.