binder: remove unused variable err
../drivers/android/binder.c:2944:7: error: unused variable 'err' [-Werror,-Wunused-variable]
 2944 |                 int err;
      |                     ^~~
1 error generated.