fuse: remove unused variable after f7fd057255c6c
From what I understand these 2 lines of code is used to check for some kind of flag
in the file being written and set p_write to true/false based on the flag.
But previous commit forced this to true therefore now it's unused?

../fs/fuse/file.c:1502:20: error: unused variable 'ff' [-Werror,-Wunused-variable]
        struct fuse_file *ff = file->private_data;
                          ^
1 error generated.

After commenting out struct fuse_file *ff = file->private_data;

../fs/fuse/file.c:1501:15: error: unused variable 'file' [-Werror,-Wunused-variable]
        struct file *file = iocb->ki_filp;
                     ^
1 error generated.