scsi: ufs: fix unused label after 67f40ffc134a5
../drivers/scsi/ufs/ufshcd.c:2925:1: error: unused label 'out' [-Werror,-Wunused-label]
out:
^~~~
1 error generated.

Signed-off-by: onettboots <blackcocopet@gmail.com>