scsi: ufs: remove unused variable
../drivers/scsi/ufs/ufshcd.h:1574:28: error: no member named 'pm_qos_vops' in 'struct ufs_hba_variant'
        if (hba->var && hba->var->pm_qos_vops &&
                        ~~~~~~~~  ^
../drivers/scsi/ufs/ufshcd.h:1575:13: error: no member named 'pm_qos_vops' in 'struct ufs_hba_variant'
                hba->var->pm_qos_vops->req_start)
                ~~~~~~~~  ^
../drivers/scsi/ufs/ufshcd.h:1576:13: error: no member named 'pm_qos_vops' in 'struct ufs_hba_variant'
                hba->var->pm_qos_vops->req_start(hba, req);
                ~~~~~~~~  ^
../drivers/scsi/ufs/ufshcd.h:1582:28: error: no member named 'pm_qos_vops' in 'struct ufs_hba_variant'
        if (hba->var && hba->var->pm_qos_vops && hba->var->pm_qos_vops->req_end)
                        ~~~~~~~~  ^
../drivers/scsi/ufs/ufshcd.h:1582:53: error: no member named 'pm_qos_vops' in 'struct ufs_hba_variant'
        if (hba->var && hba->var->pm_qos_vops && hba->var->pm_qos_vops->req_end)
                                                 ~~~~~~~~  ^
../drivers/scsi/ufs/ufshcd.h:1583:13: error: no member named 'pm_qos_vops' in 'struct ufs_hba_variant'
                hba->var->pm_qos_vops->req_end(hba, req, lock);
                ~~~~~~~~  ^
6 errors generated.
  CC      drivers/scsi/ufs/ufshcd-crypto.o
  CC      drivers/scsi/ufs/ufs-sysfs.o
make[4]: *** [../scripts/Makefile.build:366: drivers/scsi/ufs/ufs-qcom.o] Error 1
make[4]: *** Waiting for unfinished jobs....
In file included from ../drivers/scsi/ufs/ufshcd.c:49:
../drivers/scsi/ufs/ufshcd.h:1574:28: error: no member named 'pm_qos_vops' in 'struct ufs_hba_variant'
        if (hba->var && hba->var->pm_qos_vops &&
                        ~~~~~~~~  ^
../drivers/scsi/ufs/ufshcd.h:1575:13: error: no member named 'pm_qos_vops' in 'struct ufs_hba_variant'
                hba->var->pm_qos_vops->req_start)
                ~~~~~~~~  ^
../drivers/scsi/ufs/ufshcd.h:1576:13: error: no member named 'pm_qos_vops' in 'struct ufs_hba_variant'
                hba->var->pm_qos_vops->req_start(hba, req);
                ~~~~~~~~  ^
../drivers/scsi/ufs/ufshcd.h:1582:28: error: no member named 'pm_qos_vops' in 'struct ufs_hba_variant'
        if (hba->var && hba->var->pm_qos_vops && hba->var->pm_qos_vops->req_end)
                        ~~~~~~~~  ^
../drivers/scsi/ufs/ufshcd.h:1582:53: error: no member named 'pm_qos_vops' in 'struct ufs_hba_variant'
        if (hba->var && hba->var->pm_qos_vops && hba->var->pm_qos_vops->req_end)
                                                 ~~~~~~~~  ^
../drivers/scsi/ufs/ufshcd.h:1583:13: error: no member named 'pm_qos_vops' in 'struct ufs_hba_variant'
                hba->var->pm_qos_vops->req_end(hba, req, lock);
                ~~~~~~~~  ^
../drivers/scsi/ufs/ufshcd.c:11159:44: warning: shift count >= width of type [-Wshift-count-overflow]
                                                         ^~~~~~~~~~~~~~~~
../include/linux/dma-mapping.h:196:54: note: expanded from macro 'DMA_BIT_MASK'
#define DMA_BIT_MASK(n) (((n) == 64) ? ~0ULL : ((1ULL<<(n))-1))
                                                     ^ ~~~
1 warning and 6 errors generated.
make[4]: *** [../scripts/Makefile.build:366: drivers/scsi/ufs/ufshcd.o] Error 1
In file included from ../drivers/scsi/ufs/ufshcd-crypto.c:7:
../drivers/scsi/ufs/ufshcd.h:1574:28: error: no member named 'pm_qos_vops' in 'struct ufs_hba_variant'
        if (hba->var && hba->var->pm_qos_vops &&
                        ~~~~~~~~  ^
../drivers/scsi/ufs/ufshcd.h:1575:13: error: no member named 'pm_qos_vops' in 'struct ufs_hba_variant'
                hba->var->pm_qos_vops->req_start)
                ~~~~~~~~  ^
../drivers/scsi/ufs/ufshcd.h:1576:13: error: no member named 'pm_qos_vops' in 'struct ufs_hba_variant'
                hba->var->pm_qos_vops->req_start(hba, req);
                ~~~~~~~~  ^
../drivers/scsi/ufs/ufshcd.h:1582:28: error: no member named 'pm_qos_vops' in 'struct ufs_hba_variant'
        if (hba->var && hba->var->pm_qos_vops && hba->var->pm_qos_vops->req_end)
                        ~~~~~~~~  ^
../drivers/scsi/ufs/ufshcd.h:1582:53: error: no member named 'pm_qos_vops' in 'struct ufs_hba_variant'
        if (hba->var && hba->var->pm_qos_vops && hba->var->pm_qos_vops->req_end)
                                                 ~~~~~~~~  ^
../drivers/scsi/ufs/ufshcd.h:1583:13: error: no member named 'pm_qos_vops' in 'struct ufs_hba_variant'
                hba->var->pm_qos_vops->req_end(hba, req, lock);
                ~~~~~~~~  ^
In file included from ../drivers/scsi/ufs/ufs-sysfs.c:10:
In file included from ../drivers/scsi/ufs/ufs-sysfs.h:10:
../drivers/scsi/ufs/ufshcd.h:1574:28: error: no member named 'pm_qos_vops' in 'struct ufs_hba_variant'
        if (hba->var && hba->var->pm_qos_vops &&
                        ~~~~~~~~  ^
../drivers/scsi/ufs/ufshcd.h:1575:13: error: no member named 'pm_qos_vops' in 'struct ufs_hba_variant'
                hba->var->pm_qos_vops->req_start)
                ~~~~~~~~  ^
../drivers/scsi/ufs/ufshcd.h:1576:13: error: no member named 'pm_qos_vops' in 'struct ufs_hba_variant'
                hba->var->pm_qos_vops->req_start(hba, req);
                ~~~~~~~~  ^
../drivers/scsi/ufs/ufshcd.h:1582:28: error: no member named 'pm_qos_vops' in 'struct ufs_hba_variant'
        if (hba->var && hba->var->pm_qos_vops && hba->var->pm_qos_vops->req_end)
                        ~~~~~~~~  ^
../drivers/scsi/ufs/ufshcd.h:1582:53: error: no member named 'pm_qos_vops' in 'struct ufs_hba_variant'
        if (hba->var && hba->var->pm_qos_vops && hba->var->pm_qos_vops->req_end)
                                                 ~~~~~~~~  ^
../drivers/scsi/ufs/ufshcd.h:1583:13: error: no member named 'pm_qos_vops' in 'struct ufs_hba_variant'
                hba->var->pm_qos_vops->req_end(hba, req, lock);
                ~~~~~~~~  ^
6 errors generated.

Signed-off-by: onettboots <blackcocopet@gmail.com>